import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='flex flex-col h-screen justify-start'>
          <Navbar />
          <div className='flex flex-row'>
            <Sidebar />
            <div className={`${inter.className} mt-36 mb-auto container mx-auto p-4`}>
              {children}
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
